using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;

namespace Content.Client._WL.Paper.UI;

[GenerateTypedNameReferences]
public sealed partial class PaperHexColorPopup : Popup
{
    public event Action<Color>? OnColorSelected;

    public PaperHexColorPopup()
    {
        RobustXamlLoader.Load(this);

        HexInput.IsValid = value => Color.TryFromHex(value, out _);
        HexInput.OnTextChanged += _ => UpdateValidity();
        HexInput.OnTextEntered += _ => Apply();
        ConfirmButton.OnPressed += _ => Apply();
        UpdateValidity();
    }

    public void OpenPicker()
    {
        OpenAtMouse();
        HexInput.CursorPosition = HexInput.Text.Length;
        HexInput.SelectionStart = 0;
        HexInput.GrabKeyboardFocus();
    }

    private void UpdateValidity()
    {
        ConfirmButton.Disabled = !Color.TryFromHex(HexInput.Text, out _);
    }

    private void Apply()
    {
        if (!Color.TryFromHex(HexInput.Text, out var color))
            return;

        OnColorSelected?.Invoke(color);
        Close();
    }
}
