using Content.Shared._WL.Paper;
using Robust.Client.AutoGenerated;
using Robust.Client.Input;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using Robust.Shared.Utility;

namespace Content.Client._WL.Paper.UI;

[GenerateTypedNameReferences]
public sealed partial class PaperFieldEditPopup : Popup
{
    public event Action<string>? OnSaved;

    private bool _multiline;
    private int _maxLength;

    public PaperFieldEditPopup()
    {
        RobustXamlLoader.Load(this);

        SingleLineInput.IsValid = text => text.Length <= _maxLength;
        SingleLineInput.OnTextChanged += _ => UpdateFillState();
        SingleLineInput.OnTextEntered += _ => Save();
        MultilineInput.OnTextChanged += _ => UpdateFillState();
        MultilineInput.OnKeyBindDown += args =>
        {
            if (args.Function != EngineKeyFunctions.MultilineTextSubmit)
                return;

            Save();
            args.Handle();
        };
        SingleLineSaveButton.OnPressed += _ => Save();
        MultilineSaveButton.OnPressed += _ => Save();
    }

    public void OpenField(StructuredPaperElementType type, string text, int maxLength)
    {
        _multiline = type == StructuredPaperElementType.MultilineField;
        _maxLength = maxLength;

        SingleLineContainer.Visible = !_multiline;
        MultilineContainer.Visible = _multiline;
        MultilineHint.Text = Loc.GetString("paper-ui-form-field-editor-multiline-hint");

        SingleLineInput.Text = text;
        SingleLineInput.CursorPosition = text.Length;
        MultilineInput.TextRope = Rope.Leaf.Empty;
        MultilineInput.CursorPosition = new TextEdit.CursorPos();
        MultilineInput.InsertAtCursor(text);

        UpdateFillState();
        OpenAtMouse();

        if (_multiline)
        {
            MultilineInput.GrabKeyboardFocus();
            MultilineInput.CursorPosition = new TextEdit.CursorPos(text.Length, TextEdit.LineBreakBias.Top);
            MultilineInput.SelectionStart = new TextEdit.CursorPos(0, TextEdit.LineBreakBias.Top);
        }
        else
        {
            SingleLineInput.GrabKeyboardFocus();
            SingleLineInput.CursorPosition = text.Length;
            SingleLineInput.SelectionStart = 0;
        }
    }

    private void Save()
    {
        if (GetTextLength() > _maxLength)
            return;

        var text = _multiline
            ? Rope.Collapse(MultilineInput.TextRope)
            : SingleLineInput.Text;
        OnSaved?.Invoke(text);
        Close();
    }

    private void UpdateFillState()
    {
        var length = GetTextLength();
        FillStatus.Text = Loc.GetString("paper-ui-fill-level",
            ("currentLength", length),
            ("maxLength", _maxLength));
        MultilineSaveButton.Disabled = length > _maxLength;
        SingleLineSaveButton.Disabled = length > _maxLength;
    }

    private int GetTextLength()
    {
        return _multiline ? MultilineInput.TextLength : SingleLineInput.Text.Length;
    }
}
