using System.Numerics;
using System.Linq; // WL-Changes: Structured paper forms
using Content.Client.Decals.UI; // WL-Changes: Structured paper forms
using Content.Client.Resources; // WL-Changes: Structured paper forms
using Content.Client._WL.Paper.UI; // WL-Changes: Structured paper forms
using Content.Client.RichText;
using Content.Shared._WL.Paper; // WL-Changes: Structured paper forms
using Content.Shared.Paper;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.Input;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface; // WL-Changes: Structured paper forms
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;
using Robust.Client.UserInterface.RichText;
using Content.Client.UserInterface.RichText;
using Robust.Shared.Input;
using Robust.Shared.Maths; // WL-Changes: Structured paper forms
using Robust.Shared.Timing; // WL-Changes: Structured paper forms

namespace Content.Client.Paper.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class PaperWindow : BaseWindow
    {
        [Dependency] private IInputManager _inputManager = default!;
        [Dependency] private IResourceCache _resCache = default!;

        private static Color DefaultTextColor = new(25, 25, 25);

        // Default color for text which hasn't been changed using markup
        private Color _writtenTextColor = DefaultTextColor;

        // Size of resize handles around the paper
        private const int DRAG_MARGIN_SIZE = 16;

        private const float DefaultWindowHeight = 660f;
        private const float FormattingToolbarHeight = 46f;
        private const float StructureToolbarHeight = 46f;
        private const float SaveBarHeight = 36f;
        private const string SignatureEditorToken = "[sign]";

        // We keep a reference to the paper content texture that we create
        // so that we can modify it later.
        private StyleBoxTexture _paperContentTex = new();

        // The number of lines that the content image represents.
        // See PaperVisualsComponent.ContentImageNumLines.
        private float _paperContentLineScale = 1.0f;

        // If paper limits the size in one or both axes, it'll affect whether
        // we're able to resize this UI or not. Default to everything enabled:
        private DragMode _allowedResizeModes = ~DragMode.None;

        public event Action<string>? OnSaved;
        // WL-Changes-StructuredPaper-Start
        public event Action<string, string>? OnFieldSaved;
        public event Action<string>? OnFieldEditRequested;
        public event Action<string>? OnSignatureRequested;
        public event Action<string>? OnTextAppended;
        public event Action<List<StructuredPaperElement>>? OnElementsAppended;
        public event Action<List<StructuredPaperElement>>? OnStructureSaved;
        public Func<bool>? CanBeginFieldEdit;
        public PaperHandwritingStyle HandwritingStyle { get; set; } = PaperHandwritingStyle.Default;

        private readonly Dictionary<string, StructuredPaperElement> _renderedFields = new();
        private readonly Dictionary<string, StructuredPaperFieldControl> _fieldControls = new();
        private readonly PaperFieldEditPopup _fieldEditor = new();
        private readonly PaperHexColorPopup _hexColorEditor = new();
        private PaletteColorPicker? _colorPalette;
        private TextEdit? _activeMarkupEditor;
        private StructuredPaperEditorCodec? _editorCodec;
        private string _fullEditorSource = string.Empty;
        private List<StructuredPaperElement>? _renderedElements;
        private StructuredPaperFieldControl? _activeFieldControl;
        private string? _editingFieldId;
        private int _structuredTextLength;
        private bool _fullEditorActive;
        private bool _waitingForFirstLayout;
        private bool _layoutReadinessCheckQueued;
        private int _firstLayoutFrames;
        private bool _fieldsEditable;
        private bool _appendFieldsEditable;
        private bool _interactiveAppendAllowed;
        private bool _appendingText;
        private bool _fullEditorAppendMode;
        private bool _previewingStructure;
        private bool _previewBaseLegacy;
        private bool _renderedDocumentEditable;
        private readonly List<StructuredPaperElement> _previewBaseElements = new();
        private bool _hasFixedWritableHeight;
        private float? _appliedEditorChromeHeight;
        private int _freeTextLengthOffset;
        private static readonly Type[] StructuredPaperAllowedTags =
        [
            ..UserFormattableTags.BaseAllowedTags,
            typeof(StructuredPaperFieldTag),
            typeof(StructuredPaperAppendTag),
        ];
        // WL-Changes-StructuredPaper-End

        private int _MaxInputLength = -1;
        public int MaxInputLength
        {
            get
            {
                return _MaxInputLength;
            }
            set
            {
                _MaxInputLength = value;
                UpdateFillState();
            }
        }

        public PaperWindow()
        {
            IoCManager.InjectDependencies(this);
            RobustXamlLoader.Load(this);
            StructuredDocumentContainer.OnResized += UpdateStructuredFieldWidths;

            // We can't configure the RichTextLabel contents from xaml, so do it here:
            BlankPaperIndicator.SetMessage(Loc.GetString("paper-ui-blank-page-message"), null, DefaultTextColor);

            // Hook up the close button:
            CloseButton.OnPressed += _ => Close();

            Input.OnKeyBindDown += args => // Solution while TextEdit don't have events
            {
                if (args.Function == EngineKeyFunctions.MultilineTextSubmit)
                {
                    // SaveButton is disabled when we hit the max input limit. Just check
                    // that flag instead of trying to calculate the input length again
                    if (!SaveButton.Disabled)
                    {
                        RunOnSaved();
                        args.Handle();
                    }
                }
            };

            Input.OnTextChanged += args =>
            {
                UpdateFillState();
                UpdateTextEditHeight(Input, 28f);
            };
            Input.OnResized += () => UpdateTextEditHeight(Input, 28f);

            SaveButton.OnPressed += _ =>
            {
                RunOnSaved();
            };

            // WL-Changes-StructuredPaper-Start
            AddSingleLineFieldButton.OnPressed += _ => AddFullEditorElement(StructuredPaperElementType.SingleLineField);
            AddMultilineFieldButton.OnPressed += _ => AddFullEditorElement(StructuredPaperElementType.MultilineField);
            AddSignatureButton.OnPressed += _ => InsertSignatureToken();
            SaveStructureButton.OnPressed += _ => SaveFullEditor();
            PreviewStructureButton.OnPressed += _ => ToggleFullEditorPreview();
            FormatBoldButton.OnPressed += _ => WrapMarkup("[bold]", "[/bold]");
            FormatItalicButton.OnPressed += _ => WrapMarkup("[italic]", "[/italic]");
            FormatBoldItalicButton.OnPressed += _ => WrapMarkup("[bolditalic]", "[/bolditalic]");
            FormatMonoButton.OnPressed += _ => WrapMarkup("[mono]", "[/mono]");
            FormatHeading1Button.OnPressed += _ => WrapMarkup("[head=1]", "[/head]");
            FormatHeading2Button.OnPressed += _ => WrapMarkup("[head=2]", "[/head]");
            FormatHeading3Button.OnPressed += _ => WrapMarkup("[head=3]", "[/head]");
            FormatPaletteButton.OnPressed += _ => ToggleColorPalette();
            FormatHexButton.OnPressed += _ => _hexColorEditor.OpenPicker();
            FormatBulletButton.OnPressed += _ => AddBulletMarkup();
            _hexColorEditor.OnColorSelected += ApplyMarkupColor;

            FormatBoldButton.Label.FontOverride = _resCache.GetFont("/Fonts/NotoSans/NotoSans-Bold.ttf", 14);
            FormatItalicButton.Label.FontOverride = _resCache.GetFont("/Fonts/NotoSans/NotoSans-Italic.ttf", 14);
            FormatBoldItalicButton.Label.FontOverride = _resCache.GetFont("/Fonts/NotoSans/NotoSans-BoldItalic.ttf", 14);
            FormatMonoButton.Label.FontOverride = _resCache.GetFont("/EngineFonts/NotoSans/NotoSansMono-Regular.ttf", 14);
            FormatHeading1Button.Label.FontOverride = _resCache.GetFont("/Fonts/NotoSans/NotoSans-Bold.ttf", 15);
            FormatHeading2Button.Label.FontOverride = _resCache.GetFont("/Fonts/NotoSans/NotoSans-Bold.ttf", 14);
            FormatHeading3Button.Label.FontOverride = _resCache.GetFont("/Fonts/NotoSans/NotoSans-Bold.ttf", 13);
            FormatPaletteButton.Label.FontColorOverride = new Color(27, 72, 126);
            SetFormattingControlsEnabled(false);
            _fieldEditor.OnSaved += text =>
            {
                if (_editingFieldId != null)
                    OnFieldSaved?.Invoke(_editingFieldId, text);
            };
            _fieldEditor.OnPopupHide += CloseFieldEditor;
            OnClose += () =>
            {
                _fieldEditor.Close();
                _hexColorEditor.Close();
                _colorPalette?.Close();
            };
            // WL-Changes-StructuredPaper-End

            SaveButton.Text = Loc.GetString("paper-ui-save-button",
                ("keybind", _inputManager.GetKeyFunctionButtonString(EngineKeyFunctions.MultilineTextSubmit)));
        }

        /// <summary>
        ///     Initialize this UI according to <code>visuals</code> Initializes
        ///     textures, recalculates sizes, and applies some layout rules.
        /// </summary>
        public void InitVisuals(EntityUid entity, PaperVisualsComponent visuals)
        {
            _hasFixedWritableHeight = false;

            // Randomize the placement of any stamps based on the entity UID
            // so that there's some variety in different papers.
            StampDisplay.PlacementSeed = (int)entity;

            // Initialize the background:
            PaperBackground.ModulateSelfOverride = visuals.BackgroundModulate;
            var backgroundImage = visuals.BackgroundImagePath != null? _resCache.GetResource<TextureResource>(visuals.BackgroundImagePath) : null;
            if (backgroundImage != null)
            {
                var backgroundImageMode = visuals.BackgroundImageTile ? StyleBoxTexture.StretchMode.Tile : StyleBoxTexture.StretchMode.Stretch;
                var backgroundPatchMargin = visuals.BackgroundPatchMargin;
                PaperBackground.PanelOverride = new StyleBoxTexture
                {
                    Texture = backgroundImage,
                    TextureScale = visuals.BackgroundScale,
                    Mode = backgroundImageMode,
                    PatchMarginLeft = backgroundPatchMargin.Left,
                    PatchMarginBottom = backgroundPatchMargin.Bottom,
                    PatchMarginRight = backgroundPatchMargin.Right,
                    PatchMarginTop = backgroundPatchMargin.Top
                };

            }
            else
            {
                PaperBackground.PanelOverride = null;
            }


            // Then the header:
            if (visuals.HeaderImagePath != null)
            {
                HeaderImage.TexturePath = visuals.HeaderImagePath;
                HeaderImage.MinSize = HeaderImage.TextureNormal?.Size ?? Vector2.Zero;
            }

            HeaderImage.ModulateSelfOverride = visuals.HeaderImageModulate;
            HeaderImage.Margin = new Thickness(visuals.HeaderMargin.Left, visuals.HeaderMargin.Top,
                    visuals.HeaderMargin.Right, visuals.HeaderMargin.Bottom);

            // Then the footer
            if (visuals.FooterImagePath is {} path)
            {
                FooterImage.TexturePath = path.ToString();
                FooterImage.MinSize = FooterImage.TextureNormal?.Size ?? Vector2.Zero;
            }

            FooterImage.ModulateSelfOverride = visuals.FooterImageModulate;
            FooterImage.Margin = new Thickness(visuals.FooterMargin.Left, visuals.FooterMargin.Top,
                    visuals.FooterMargin.Right, visuals.FooterMargin.Bottom);

            PaperContent.ModulateSelfOverride = visuals.ContentImageModulate;
            _writtenTextColor = visuals.DefaultTextColor ?? DefaultTextColor;

            var contentImage = visuals.ContentImagePath != null ? _resCache.GetResource<TextureResource>(visuals.ContentImagePath) : null;
            if (contentImage != null)
            {
                // Setup the paper content texture, but keep a reference to it, as we can't set
                // some font-related properties here. We'll fix those up later, in Draw()
                _paperContentTex = new StyleBoxTexture
                {
                    Texture = contentImage,
                    Mode = StyleBoxTexture.StretchMode.Tile,
                };
                PaperContent.PanelOverride = _paperContentTex;
                _paperContentLineScale = visuals.ContentImageNumLines;
            }

            PaperContent.Margin = new Thickness(
                    visuals.ContentMargin.Left, visuals.ContentMargin.Top,
                    visuals.ContentMargin.Right, visuals.ContentMargin.Bottom);

            if (visuals.MaxWritableArea != null)
            {
                var a = (Vector2)visuals.MaxWritableArea;
                // Paper has requested that this has a maximum area that you can write on.
                // So, we'll make the window non-resizable and fix the size of the content.
                // Ideally, would like to be able to allow resizing only one direction.
                ScrollingContents.MinSize = Vector2.Zero;
                ScrollingContents.MinSize = a;

                if (a.X > 0.0f)
                {
                    ScrollingContents.MaxWidth = a.X;
                    _allowedResizeModes &= ~(DragMode.Left | DragMode.Right);

                    // Since this dimension has been specified by the user, we
                    // need to undo the SetSize which was configured in the xaml.
                    // Controls use NaNs to indicate unset for this value.
                    // This is leaky - there should be a method for this
                    SetWidth = float.NaN;
                }

                if (a.Y > 0.0f)
                {
                    _hasFixedWritableHeight = true;
                    ScrollingContents.MaxHeight = a.Y;
                    _allowedResizeModes &= ~(DragMode.Top | DragMode.Bottom);
                    SetHeight = float.NaN;
                }
            }
        }

        /// <summary>
        ///     Control interface. We'll mostly rely on the children to do the drawing
        ///     but in order to get lines on paper to match up with the rich text labels,
        ///     we need to do a small calculation to sync them up.
        /// </summary>
        protected override void Draw(DrawingHandleScreen handle)
        {
            // Now do the deferred setup of the written area. At the point
            // that InitVisuals runs, the label hasn't had it's style initialized
            // so we need to get some info out now:
            if (WrittenTextLabel.TryGetStyleProperty<Font>("font", out var font))
            {
                float fontLineHeight = font.GetLineHeight(1.0f);
                // This positions the texture so the font baseline is on the bottom:
                _paperContentTex.ExpandMarginTop = font.GetDescent(UIScale);
                // And this scales the texture so that it's a single text line:
                var scaleY = (_paperContentLineScale * fontLineHeight) / _paperContentTex.Texture?.Height ?? fontLineHeight;
                _paperContentTex.TextureScale = new Vector2(1, scaleY);

                // Now, we might need to add some padding to the text to ensure
                // that, even if a header is specified, the text will line up with
                // where the content image expects the font to be rendered (i.e.,
                // adjusting the height of the header image shouldn't cause the
                // text to be offset from a line)
                {
                    var headerHeight = HeaderImage.Size.Y + HeaderImage.Margin.Top + HeaderImage.Margin.Bottom;
                    var headerInLines = headerHeight / (fontLineHeight * _paperContentLineScale);
                    var paddingRequiredInLines = (float)Math.Ceiling(headerInLines) - headerInLines;
                    var verticalMargin = fontLineHeight * paddingRequiredInLines * _paperContentLineScale;
                    TextAlignmentPadding.Margin = new Thickness(0.0f, verticalMargin, 0.0f, 0.0f);
                }
            }

            base.Draw(handle);
        }

        // WL-Changes-StructuredPaper-Start
        public void PrepareForFirstReveal()
        {
            // Keep the whole tree participating in layout, but do not show the paper shell before its
            // dynamically-created rich text controls have been arranged.
            ModulateSelfOverride = Color.Transparent;
            _waitingForFirstLayout = true;
            _layoutReadinessCheckQueued = false;
            _firstLayoutFrames = 0;
        }

        protected override void FrameUpdate(FrameEventArgs args)
        {
            base.FrameUpdate(args);

            if (!_waitingForFirstLayout)
                return;

            if (_layoutReadinessCheckQueued)
                return;

            if (++_firstLayoutFrames > 30)
            {
                ModulateSelfOverride = null;
                _waitingForFirstLayout = false;
                return;
            }

            _layoutReadinessCheckQueued = true;
            UserInterfaceManager.DeferAction(() =>
            {
                _layoutReadinessCheckQueued = false;
                if (_waitingForFirstLayout && IsLayoutReady(ContentsRoot))
                {
                    ModulateSelfOverride = null;
                    _waitingForFirstLayout = false;
                }
            });
        }

        private static bool IsLayoutReady(Control control)
        {
            if (!control.Visible && !control.ReservesSpace)
                return true;

            if (!control.IsMeasureValid || !control.IsArrangeValid)
                return false;

            if (control is RichTextLabel label &&
                !string.IsNullOrEmpty(label.GetMessage()) &&
                (label.DesiredSize.Y <= 0 || label.Size.Y <= 0))
            {
                return false;
            }

            foreach (var child in control.Children)
            {
                if (!IsLayoutReady(child))
                    return false;
            }

            return true;
        }
        // WL-Changes-StructuredPaper-End

        /// <summary>
        ///     Initialize the paper contents, i.e. the text typed by the
        ///     user and any stamps that have peen put on the page.
        /// </summary>
        public void Populate(PaperComponent.PaperBoundUserInterfaceState state, bool isEditor)
        {
            bool isEditing = state.Mode == PaperComponent.PaperAction.Write && isEditor;
            // WL-Changes-StructuredPaper-Start
            var isStructured = state.Elements != null;
            var isFreeTextEditing = isEditing && state.EditAccess == PaperEditAccess.FreeText;
            var isFieldEditing = isEditing && state.EditAccess == PaperEditAccess.Fields;
            var isFullEditing = isEditing && state.EditAccess == PaperEditAccess.Full;
            _appendFieldsEditable = isFieldEditing;
            if (!isEditing)
            {
                _fieldEditor.Close();
                CloseFieldEditor();
            }
            var isAppendingText = isFieldEditing && _appendingText;
            var isDraftEditing = isFreeTextEditing || isAppendingText;
            _interactiveAppendAllowed = !isFieldEditing;
            _structuredTextLength = state.Elements?.Sum(element =>
                element.Text.Length + (element.NewLineAfter ? 1 : 0))
                ?? state.Text.Length;
            _freeTextLengthOffset = isFreeTextEditing && state.Text.Length > 0
                ? state.Text.Length + (state.Text.EndsWith('\n') ? 0 : 1)
                : isAppendingText && MaxInputLength >= 0
                    ? MaxInputLength - Math.Min(
                        StructuredPaperElement.DefaultMultilineMaxLength,
                        Math.Max(0, MaxInputLength - _structuredTextLength -
                            (state.Elements is { Count: > 0 } && !state.Elements[^1].NewLineAfter ? 1 : 0)))
                    : 0;
            // WL-Changes-StructuredPaper-End
            bool wasEditing = InputContainer.Visible;
            InputContainer.Visible = false; // WL-Changes: Structured paper forms
            EditButtons.Visible = false; // WL-Changes: Structured paper forms
            // WL-Changes-StructuredPaper-Start
            var editorMode = isFullEditing || isDraftEditing;
            if (editorMode && (!_fullEditorActive || _fullEditorAppendMode != isDraftEditing))
            {
                SetFullEditorPreview(false);
                PopulateFullEditor(state, isDraftEditing);
            }

            var showingPreview = editorMode && _previewingStructure;
            StructuredDocumentContainer.Visible = showingPreview || isStructured && !isFullEditing;
            FullEditorContainer.Visible = editorMode && !showingPreview;
            var editorTopMargin = isDraftEditing && state.Elements is { Count: > 0 } &&
                state.Elements[^1].Type == StructuredPaperElementType.StaticText
                    ? 2f
                    : 0f;
            FullEditorContainer.Margin = new Thickness(4, editorTopMargin, 4, 0);
            FullEditorToolbar.Visible = editorMode;
            FullEditorFormattingToolbar.Visible = editorMode && !showingPreview;
            UpdateWindowHeight(editorMode && !showingPreview, false, false);
            var displayedElements = isDraftEditing && !showingPreview
                ? BuildAppendBase(state.Elements)
                : state.Elements;
            PopulateStructuredDocument(showingPreview ? BuildFullEditorPreview() : displayedElements,
                isFieldEditing && !showingPreview);
            _fullEditorActive = editorMode;
            // WL-Changes-StructuredPaper-End

            // For premade documents, we want to be able to edit them rather than
            // replace them.
            if (!wasEditing && isFreeTextEditing)
            {
                // We can get repeated messages with state.Mode == Write if another
                // player opens the UI for reading. In this case, don't update the
                // text input, as this player is currently writing new text and we
                // don't want to lose any text they already input.
                Input.TextRope = Rope.Leaf.Empty;
                Input.CursorPosition = new TextEdit.CursorPos();
            }
            UpdateFillState();

            if (!isStructured)
            {
                var msg = new FormattedMessage();
                msg.AddMarkupPermissive(state.Text);
                for (var i = 0; i <= state.StampedBy.Count * 3 + 1; i++)
                    msg.AddMarkupPermissive("\r\n");

                WrittenTextLabel.SetMessage(msg, UserFormattableTags.BaseAllowedTags, _writtenTextColor);
            }

            WrittenTextLabel.Visible = !showingPreview && !isStructured && state.Text.Length > 0 &&
                (!isEditing || isFreeTextEditing); // WL-Changes: Structured paper forms
            BlankPaperIndicator.Visible = !isEditing &&
                (!isStructured && state.Text.Length == 0 || isStructured && state.Elements!.Count == 0); // WL-Changes: Structured paper forms

            StampDisplay.RemoveAllChildren();
            StampDisplay.RemoveStamps();
            foreach(var stamper in state.StampedBy)
            {
                // WL-Changes-start
                var stamp = new StampWidget();
                stamp.UpdateVisuals(stamper);

                StampDisplay.AddStamp(stamp);
                // WL-Changes-end
            }
        }

        // WL-Changes-StructuredPaper-Start
        private void PopulateStructuredDocument(List<StructuredPaperElement>? elements, bool editingFields)
        {
            _fieldsEditable = editingFields;

            var canReuseLayout = elements != null &&
                _renderedDocumentEditable == editingFields &&
                CanReuseStructuredDocument(elements);

            if (canReuseLayout)
            {
                UpdateStructuredFields(elements!, editingFields);
                return;
            }

            if (IsOpen && !canReuseLayout && _renderedElements == null)
                PrepareForFirstReveal();

            StructuredDocumentContainer.RemoveAllChildren();
            _fieldControls.Clear();
            _renderedFields.Clear();
            _renderedElements = elements?.Select(element => element.Copy()).ToList();
            _renderedDocumentEditable = editingFields;
            if (elements == null)
                return;

            var label = new RichTextLabel
            {
                HorizontalExpand = true,
                VerticalAlignment = Control.VAlignment.Top,
                StyleClasses = { "PaperWrittenText" },
            };

            label.SetMessage(BuildStructuredMessage(elements, editingFields), StructuredPaperAllowedTags, _writtenTextColor);
            StructuredDocumentContainer.AddChild(label);
            RegisterStructuredFieldControls(label);
            UpdateStructuredFields(elements, editingFields);
        }

        private void UpdateStructuredFields(IReadOnlyList<StructuredPaperElement> elements, bool editingFields)
        {
            _renderedFields.Clear();
            foreach (var element in elements)
            {
                if (!IsFillableField(element.Type))
                    continue;

                _renderedFields[element.Id] = element.Copy();
                if (!_fieldControls.TryGetValue(element.Id, out var field))
                    continue;

                field.UpdateContent(
                    element.Text,
                    GetRevisions(element),
                    Loc.GetString("paper-ui-form-write-field"),
                    editingFields,
                    element.Id == _editingFieldId,
                    element.HandwritingStyle,
                    element.Type == StructuredPaperElementType.Signature &&
                    !_previewingStructure);
            }

            _renderedElements = elements.Select(element => element.Copy()).ToList();

        }

        private static IReadOnlyList<PaperFieldRevision> GetRevisions(StructuredPaperElement element)
        {
            if (string.IsNullOrWhiteSpace(element.PreviousText))
                return element.Revisions;

            var revisions = element.Revisions.Select(revision => revision.Copy()).ToList();
            revisions.Add(new PaperFieldRevision(element.PreviousText, element.PreviousHandwritingStyle));
            return revisions;
        }

        private bool CanReuseStructuredDocument(IReadOnlyList<StructuredPaperElement> elements)
        {
            if (_renderedElements == null)
                return false;

            if (_renderedElements.Count != elements.Count)
                return false;

            for (var i = 0; i < elements.Count; i++)
            {
                var previous = _renderedElements[i];
                var current = elements[i];
                if (previous.Id != current.Id ||
                    previous.Type != current.Type ||
                    previous.NewLineAfter != current.NewLineAfter ||
                    previous.MaxLength != current.MaxLength ||
                    !IsFillableField(current.Type) && previous.Text != current.Text)
                {
                    return false;
                }
            }

            return true;
        }

        private FormattedMessage BuildStructuredMessage(List<StructuredPaperElement> elements, bool editable)
        {
            var message = new FormattedMessage();

            foreach (var element in elements)
            {
                if (element.Type == StructuredPaperElementType.StaticText)
                {
                    message.AddMarkupPermissive(element.Text);
                }
                else if (element.Type == StructuredPaperElementType.HandwrittenText)
                {
                    StructuredPaperFieldControl.AddFormattedHandwriting(message, element.Text, element.HandwritingStyle);
                }
                else
                {
                    _renderedFields[element.Id] = element.Copy();
                    var attributes = new Dictionary<string, MarkupParameter>
                    {
                        ["text"] = new(element.Text),
                        ["previous"] = new(element.PreviousText),
                        ["placeholder"] = new(Loc.GetString("paper-ui-form-write-field")),
                        ["editable"] = new(editable ? 1 : 0),
                        ["selected"] = new(element.Id == _editingFieldId ? 1 : 0),
                        ["multiline"] = new(element.Type == StructuredPaperElementType.MultilineField ? 1 : 0),
                        ["signature"] = new(element.Type == StructuredPaperElementType.Signature ? 1 : 0),
                        ["signature-action"] = new(element.Type == StructuredPaperElementType.Signature &&
                            !_previewingStructure ? 1 : 0),
                        ["style"] = new((long) element.HandwritingStyle),
                        ["previous-style"] = new((long) element.PreviousHandwritingStyle),
                    };

                    message.PushTag(new MarkupNode(StructuredPaperFieldTag.TagName, new MarkupParameter(element.Id), attributes), true);
                }

                if (element.NewLineAfter)
                    message.PushNewline();
            }

            if (editable)
            {
                if (elements.Count > 0 && !elements[^1].NewLineAfter)
                    message.PushNewline();

                message.PushTag(new MarkupNode(StructuredPaperAppendTag.TagName), true);
            }

            return message;
        }

        private void RegisterStructuredFieldControls(RichTextLabel label)
        {
            foreach (var control in label.Controls)
            {
                if (control is StructuredPaperAppendControl append)
                {
                    append.OnPressed += _ => OpenAppendEditor();
                    continue;
                }

                if (control is not StructuredPaperFieldControl field)
                    continue;

                _fieldControls[field.FieldId] = field;
                var fieldId = field.FieldId;
                field.OnPressed += _ =>
                {
                    if (_renderedFields.TryGetValue(fieldId, out var current))
                    {
                        if (_fieldsEditable)
                            OpenFieldEditor(current, field);
                        else
                            RequestFieldEditor(fieldId, field);
                    }
                };
                field.OnSignatureRequested += () => OnSignatureRequested?.Invoke(fieldId);

                if (fieldId == _editingFieldId)
                {
                    _activeFieldControl = field;
                    field.SetSelected(true);
                }

            }

            UpdateStructuredFieldWidths();
        }

        private void UpdateStructuredFieldWidths()
        {
            var availableWidth = StructuredDocumentContainer.Width - 8;
            if (availableWidth <= 0)
                return;

            foreach (var field in _fieldControls.Values)
                field.SetDocumentWidth(availableWidth);
        }

        private void RequestFieldEditor(string fieldId, StructuredPaperFieldControl field)
        {
            if (!_renderedFields.TryGetValue(fieldId, out var element))
                return;

            // The server still authorizes the session and validates the eventual write. Opening the local editor
            // immediately avoids making the interaction wait for a full network round-trip.
            if (CanBeginFieldEdit?.Invoke() == false)
            {
                OnFieldEditRequested?.Invoke(fieldId);
                return;
            }

            CloseFieldEditor();
            _editingFieldId = fieldId;
            _activeFieldControl = field;
            field.SetSelected(true);
            OpenFieldEditor(element, field);
        }

        private void OpenFieldEditor(StructuredPaperElement element, StructuredPaperFieldControl field)
        {
            CloseFieldEditor();
            _appendingText = false;
            _editingFieldId = element.Id;
            _activeFieldControl = field;
            field.SetSelected(true);

            var remainingPaperLength = MaxInputLength < 0
                ? int.MaxValue
                : Math.Max(0, MaxInputLength - _structuredTextLength + element.Text.Length);
            var maxLength = Math.Min(element.GetMaxLength(), remainingPaperLength);
            _fieldEditor.OpenField(element.Type, element.Text, maxLength);
        }

        private void OpenAppendEditor()
        {
            CloseFieldEditor();
            _appendingText = true;
            SetFullEditorPreview(false);
            if (MaxInputLength >= 0)
            {
                var separatorLength = _renderedElements is { Count: > 0 } &&
                    !_renderedElements[^1].NewLineAfter
                        ? 1
                        : 0;
                var availableLength = Math.Min(
                    StructuredPaperElement.DefaultMultilineMaxLength,
                    Math.Max(0, MaxInputLength - _structuredTextLength - separatorLength));
                _freeTextLengthOffset = MaxInputLength - availableLength;
            }
            _fullEditorAppendMode = true;
            _previewBaseLegacy = false;
            _previewBaseElements.Clear();
            if (_renderedElements != null)
                _previewBaseElements.AddRange(_renderedElements.Select(element => element.Copy()));
            _editorCodec = StructuredPaperEditorCodec.Create([], true, out _fullEditorSource);
            RebuildFullEditor();
            _fullEditorActive = true;
            FullEditorContainer.Visible = true;
            FullEditorToolbar.Visible = true;
            FullEditorFormattingToolbar.Visible = true;
            AddSingleLineFieldButton.Visible = _interactiveAppendAllowed;
            AddMultilineFieldButton.Visible = _interactiveAppendAllowed;
            AddSignatureButton.Visible = _interactiveAppendAllowed;
            UpdateWindowHeight(true, false, false);
            UserInterfaceManager.DeferAction(() =>
            {
                ScrollingContents.VScrollTarget = float.PositiveInfinity;
            });
        }

        private void CloseFieldEditor()
        {
            var wasAppending = _appendingText;
            if (_activeFieldControl != null &&
                _editingFieldId != null)
            {
                _activeFieldControl.SetSelected(false);
            }

            _activeFieldControl = null;
            _editingFieldId = null;
            _appendingText = false;
            if (wasAppending)
            {
                FullEditorContainer.Visible = false;
                FullEditorToolbar.Visible = false;
                FullEditorFormattingToolbar.Visible = false;
                UpdateWindowHeight(false, false, false);
                SetActiveMarkupEditor(null);
            }
        }

        private void PopulateFullEditor(PaperComponent.PaperBoundUserInterfaceState? state, bool appendOnly = false)
        {
            _fullEditorAppendMode = appendOnly;
            var interactiveElementsVisible = !appendOnly || _interactiveAppendAllowed;
            AddSingleLineFieldButton.Visible = interactiveElementsVisible;
            AddMultilineFieldButton.Visible = interactiveElementsVisible;
            AddSignatureButton.Visible = interactiveElementsVisible;
            _previewBaseElements.Clear();
            _previewBaseLegacy = appendOnly && state?.Elements == null && !string.IsNullOrEmpty(state?.Text);
            if (appendOnly && state?.Elements != null)
                _previewBaseElements.AddRange(state.Elements.Select(element => element.Copy()));
            else if (_previewBaseLegacy)
                _previewBaseElements.Add(new StructuredPaperElement(
                    "preview-legacy",
                    StructuredPaperElementType.StaticText,
                    state!.Text,
                    newLineAfter: !state.Text.EndsWith('\n')));

            var incoming = appendOnly
                ? new List<StructuredPaperElement>
                {
                    new(string.Empty, StructuredPaperElementType.HandwrittenText, string.Empty)
                    {
                        HandwritingStyle = HandwritingStyle,
                    },
                }
                : state?.Elements ?? new List<StructuredPaperElement>
                {
                    new(string.Empty, StructuredPaperElementType.StaticText, state?.Text ?? string.Empty),
                };

            if (incoming.Count == 0)
                incoming.Add(new StructuredPaperElement(string.Empty, StructuredPaperElementType.StaticText, string.Empty));

            _editorCodec = StructuredPaperEditorCodec.Create(incoming, appendOnly, out _fullEditorSource);
            RebuildFullEditor();
        }

        private static List<StructuredPaperElement>? BuildAppendBase(
            IReadOnlyList<StructuredPaperElement>? elements)
        {
            if (elements == null)
                return null;

            var displayed = elements.Select(element => element.Copy()).ToList();
            if (displayed.Count > 0)
                displayed[^1].NewLineAfter = false;

            return displayed;
        }

        private void ToggleFullEditorPreview()
        {
            SetFullEditorPreview(PreviewStructureButton.Pressed);
        }

        private void SetFullEditorPreview(bool preview)
        {
            _previewingStructure = preview;
            PreviewStructureButton.Pressed = preview;
            AddSingleLineFieldButton.Disabled = preview;
            AddMultilineFieldButton.Disabled = preview;
            AddSignatureButton.Disabled = preview || _activeMarkupEditor == null;
            if (!_fullEditorActive)
                return;

            if (preview)
            {
                PopulateStructuredDocument(BuildFullEditorPreview(), false);
            }
            else if (_fullEditorAppendMode)
            {
                PopulateStructuredDocument(
                    _previewBaseLegacy ? null : BuildAppendBase(_previewBaseElements),
                    _appendFieldsEditable);
            }

            StructuredDocumentContainer.Visible = preview || _fullEditorAppendMode && !_previewBaseLegacy;
            WrittenTextLabel.Visible = !preview && _fullEditorAppendMode && _previewBaseLegacy;
            FullEditorContainer.Visible = !preview;
            FullEditorFormattingToolbar.Visible = !preview;
            UpdateWindowHeight(!preview, false, false);
        }

        private List<StructuredPaperElement> BuildFullEditorPreview()
        {
            var preview = _fullEditorAppendMode
                ? _previewBaseElements.Select(element => element.Copy()).ToList()
                : new List<StructuredPaperElement>();
            if (!TryParseFullEditor(out var draft))
                return preview;

            if (preview.Count > 0 && draft.Count > 0 && !preview[^1].NewLineAfter)
                preview[^1].NewLineAfter = true;
            preview.AddRange(draft);

            var reservedIds = preview
                .Select(element => element.Id)
                .Where(id => !string.IsNullOrWhiteSpace(id))
                .ToHashSet();
            var usedIds = new HashSet<string>();
            for (var i = 0; i < preview.Count; i++)
            {
                if (string.IsNullOrWhiteSpace(preview[i].Id) || !usedIds.Add(preview[i].Id))
                {
                    var previewId = $"preview-{i}";
                    var suffix = 0;
                    while (reservedIds.Contains(previewId) || !usedIds.Add(previewId))
                        previewId = $"preview-{i}-{++suffix}";
                    preview[i].Id = previewId;
                }
            }

            return preview;
        }

        private void SaveFullEditor()
        {
            if (!TryParseFullEditor(out var elements))
                return;

            if (_fullEditorAppendMode)
            {
                _appendingText = false;
                OnElementsAppended?.Invoke(elements);
            }
            else
                OnStructureSaved?.Invoke(elements);
        }

        private void AddFullEditorElement(StructuredPaperElementType type)
        {
            if (_activeMarkupEditor is not { } input)
                return;

            var token = type switch
            {
                StructuredPaperElementType.SingleLineField => "[f]",
                StructuredPaperElementType.MultilineField => "[lf]",
                _ => throw new ArgumentOutOfRangeException(nameof(type)),
            };

            input.InsertAtCursor(token);
            input.GrabKeyboardFocus();
        }

        private void InsertSignatureToken()
        {
            if (_activeMarkupEditor is not { } input)
                return;

            input.InsertAtCursor(SignatureEditorToken);
            input.GrabKeyboardFocus();
        }

        private void RebuildFullEditor()
        {
            SetActiveMarkupEditor(null);
            FullEditorElements.RemoveAllChildren();
            var compact = _fullEditorAppendMode &&
                (_previewBaseLegacy || _previewBaseElements.Count > 0);
            var panel = new PanelContainer
            {
                StyleIdentifier = "PaperEditorBackground",
                HorizontalExpand = true,
                VerticalExpand = !compact,
                Margin = new Thickness(0),
            };
            var input = CreateSourceTextEdit(_fullEditorSource, compact);
            if (_fullEditorAppendMode)
                input.StyleClasses.Add(GetHandwritingEditorClass(HandwritingStyle));
            input.OnTextChanged += _ =>
            {
                _fullEditorSource = Rope.Collapse(input.TextRope);
                if (compact)
                    UpdateTextEditHeight(input, 28f);
                UpdateFullEditorValidation();
            };
            input.OnKeyBindDown += _ => SetActiveMarkupEditor(input);
            panel.AddChild(input);
            FullEditorElements.AddChild(panel);
            SetActiveMarkupEditor(input);
            UpdateFullEditorValidation();
            UserInterfaceManager.DeferAction(() =>
            {
                input.GrabKeyboardFocus();
                if (compact)
                    UpdateTextEditHeight(input, 28f);
            });
        }

        private bool TryParseFullEditor(out List<StructuredPaperElement> elements)
        {
            elements = new List<StructuredPaperElement>();
            return _editorCodec != null &&
                _editorCodec.TryParse(_fullEditorSource, _fullEditorAppendMode, HandwritingStyle, out elements);
        }

        private void UpdateFullEditorValidation()
        {
            var valid = TryParseFullEditor(out var elements);
            var tooLong = false;
            if (valid && MaxInputLength >= 0)
            {
                var length = elements.Sum(element =>
                    element.Text.Length + (element.NewLineAfter ? 1 : 0));
                tooLong = length > MaxInputLength - _freeTextLengthOffset;
                valid = !tooLong;
            }

            SaveStructureButton.Disabled = !valid;
            PreviewStructureButton.Disabled = !valid;
            FullEditorValidationStatus.Visible = !valid;
            FullEditorValidationStatus.Text = tooLong
                ? Loc.GetString("paper-ui-form-editor-too-long")
                : Loc.GetString("paper-ui-form-editor-invalid-tags");
            SaveStructureButton.ToolTip = valid
                ? Loc.GetString("paper-ui-form-save-structure-tooltip")
                : FullEditorValidationStatus.Text;
        }

        private static bool IsFillableField(StructuredPaperElementType type)
        {
            return type is StructuredPaperElementType.SingleLineField or
                StructuredPaperElementType.MultilineField or
                StructuredPaperElementType.SignatureField or
                StructuredPaperElementType.Signature;
        }

        private TextEdit CreateSourceTextEdit(string text, bool compact)
        {
            var input = new TextEdit
            {
                HorizontalExpand = true,
                VerticalExpand = !compact,
                MinHeight = compact ? 28 : 560,
                MaxHeight = compact ? 28 : float.NaN,
                Margin = new Thickness(0),
                StyleClasses = { "PaperTextEdit" },
            };
            input.InsertAtCursor(text);
            input.CursorPosition = new TextEdit.CursorPos(0, TextEdit.LineBreakBias.Top);
            if (compact)
                input.OnResized += () => UpdateTextEditHeight(input, 28f);
            return input;
        }

        private void UpdateTextEditHeight(TextEdit input, float minimumHeight = 24f)
        {
            if (input.Width <= 0)
                return;

            var font = input.TryGetStyleProperty<Font>("font", out var styledFont)
                ? styledFont
                : _resCache.GetFont("/Fonts/NotoSans/NotoSans-Regular.ttf", 12);
            var availableWidth = Math.Max(40f, input.Width - 18f);
            var lineCount = 1;
            var lineWidth = 0f;

            foreach (var rune in Rope.EnumerateRunes(input.TextRope))
            {
                if (rune.Value == '\n')
                {
                    lineCount++;
                    lineWidth = 0;
                    continue;
                }

                if (!font.TryGetCharMetrics(rune, 1f, out var metrics))
                    continue;

                if (lineWidth > 0 && lineWidth + metrics.Advance > availableWidth)
                {
                    lineCount++;
                    lineWidth = 0;
                }

                lineWidth += metrics.Advance;
            }

            var height = Math.Max(minimumHeight, lineCount * font.GetLineHeight(1f) + 6f);
            if (MathHelper.CloseTo(input.MinHeight, height))
                return;

            input.MinHeight = height;
            input.MaxHeight = height;
        }

        private void UpdateWindowHeight(bool fullEditing, bool freeTextEditing, bool appendingText)
        {
            if (_hasFixedWritableHeight)
                return;

            var editorChromeHeight = 0f;
            if (fullEditing || freeTextEditing)
                editorChromeHeight += FormattingToolbarHeight;
            if (fullEditing)
                editorChromeHeight += StructureToolbarHeight;
            if (freeTextEditing || appendingText)
                editorChromeHeight += SaveBarHeight;

            if (_appliedEditorChromeHeight == editorChromeHeight)
                return;

            _appliedEditorChromeHeight = editorChromeHeight;

            MinHeight = editorChromeHeight > 0
                ? DefaultWindowHeight + editorChromeHeight
                : 150f;
            SetHeight = editorChromeHeight > 0
                ? DefaultWindowHeight + editorChromeHeight
                : DefaultWindowHeight;
        }

        private static string GetHandwritingEditorClass(PaperHandwritingStyle style)
        {
            return style switch
            {
                PaperHandwritingStyle.Neat => "PaperHandwritingNeat",
                PaperHandwritingStyle.Quick => "PaperHandwritingQuick",
                PaperHandwritingStyle.Formal => "PaperHandwritingFormal",
                PaperHandwritingStyle.Heavy => "PaperHandwritingHeavy",
                PaperHandwritingStyle.Messy => "PaperHandwritingMessy",
                _ => "PaperHandwritingDefault",
            };
        }

        private void SetActiveMarkupEditor(TextEdit? input)
        {
            _activeMarkupEditor = input;
            SetFormattingControlsEnabled(input != null);
        }

        private void SetFormattingControlsEnabled(bool enabled)
        {
            foreach (var button in GetFormattingButtons())
                button.Disabled = !enabled;

            AddSignatureButton.Disabled = !enabled;

            FullEditorFormattingToolbar.ToolTip = enabled
                ? null
                : Loc.GetString("paper-ui-form-format-select-text");
        }

        private Button[] GetFormattingButtons()
        {
            return
            [
                FormatBoldButton,
                FormatItalicButton,
                FormatBoldItalicButton,
                FormatMonoButton,
                FormatHeading1Button,
                FormatHeading2Button,
                FormatHeading3Button,
                FormatPaletteButton,
                FormatHexButton,
                FormatBulletButton,
            ];
        }

        private void WrapMarkup(string openingTag, string closingTag)
        {
            if (_activeMarkupEditor is not { } input)
                return;

            var lower = input.SelectionLower.Index;
            var upper = input.SelectionUpper.Index;
            var text = Rope.Collapse(input.TextRope);
            var selected = text.Substring(lower, upper - lower);
            input.InsertAtCursor(openingTag + selected + closingTag);

            var innerStart = lower + openingTag.Length;
            var innerEnd = innerStart + selected.Length;
            input.CursorPosition = new TextEdit.CursorPos(innerEnd, TextEdit.LineBreakBias.Top);
            input.SelectionStart = new TextEdit.CursorPos(innerStart, TextEdit.LineBreakBias.Top);
            input.GrabKeyboardFocus();
        }

        private void AddBulletMarkup()
        {
            if (_activeMarkupEditor is not { } input)
                return;

            const string bulletTag = "[bullet]";
            var text = Rope.Collapse(input.TextRope);
            var lower = input.SelectionLower.Index;
            var upper = input.SelectionUpper.Index;
            var lineStart = lower == 0 ? 0 : text.LastIndexOf('\n', lower - 1) + 1;
            var lineEnd = upper;
            if (lower == upper)
            {
                var nextLine = text.IndexOf('\n', upper);
                lineEnd = nextLine < 0 ? text.Length : nextLine;
            }

            var section = text.Substring(lineStart, lineEnd - lineStart);
            var replacement = bulletTag + section.Replace("\n", $"\n{bulletTag}");
            input.CursorPosition = new TextEdit.CursorPos(lineEnd, TextEdit.LineBreakBias.Top);
            input.SelectionStart = new TextEdit.CursorPos(lineStart, TextEdit.LineBreakBias.Top);
            input.InsertAtCursor(replacement);
            input.GrabKeyboardFocus();
        }

        private void ToggleColorPalette()
        {
            if (_activeMarkupEditor == null)
                return;

            if (_colorPalette == null)
            {
                _colorPalette = new PaletteColorPicker();
                _colorPalette.PaletteList.OnItemSelected += args =>
                {
                    if (args.ItemList.GetSelected().FirstOrDefault()?.Metadata is not Color color)
                        return;

                    ApplyMarkupColor(color);
                    _colorPalette.Close();
                };
            }

            if (_colorPalette.IsOpen)
                _colorPalette.Close();
            else
                _colorPalette.OpenCenteredLeft();
        }

        private void ApplyMarkupColor(Color color)
        {
            WrapMarkup($"[color={color.ToHexNoAlpha()}]", "[/color]");
        }

        // WL-Changes-StructuredPaper-End

        /// <summary>
        ///     BaseWindow interface. Allow users to drag UI around by grabbing
        ///     anywhere on the page (like FancyWindow) but try to calculate
        ///     reasonable dragging bounds because this UI can have round corners,
        ///     and it can be hard to judge where to click to resize.
        /// </summary>
        protected override DragMode GetDragModeFor(Vector2 relativeMousePos)
        {
            var mode = DragMode.None;

            // Be quite generous with resize margins:
            if (relativeMousePos.Y < DRAG_MARGIN_SIZE)
            {
                mode |= DragMode.Top;
            }
            else if (relativeMousePos.Y > Size.Y - DRAG_MARGIN_SIZE)
            {
                mode |= DragMode.Bottom;
            }

            if (relativeMousePos.X < DRAG_MARGIN_SIZE)
            {
                mode |= DragMode.Left;
            }
            else if (relativeMousePos.X > Size.X - DRAG_MARGIN_SIZE)
            {
                mode |= DragMode.Right;
            }

            if((mode & _allowedResizeModes) == DragMode.None)
            {
                return DragMode.Move;
            }
            return mode & _allowedResizeModes;
        }

        private void RunOnSaved()
        {
            // Prevent further saving while text processing still in
            SaveButton.Disabled = true;
            var text = Rope.Collapse(Input.TextRope);
            if (_appendingText)
            {
                _appendingText = false;
                InputContainer.Visible = false;
                EditButtons.Visible = false;
                SetActiveMarkupEditor(null);
                Input.TextRope = Rope.Leaf.Empty;
                Input.CursorPosition = new TextEdit.CursorPos();
                UpdateWindowHeight(false, false, false);
                OnTextAppended?.Invoke(text);
                return;
            }

            OnSaved?.Invoke(text);
        }

        private void UpdateFillState()
        {
            if (MaxInputLength != -1)
            {
                var inputLength = Input.TextLength;
                var availableLength = Math.Max(0, MaxInputLength - _freeTextLengthOffset);

                FillStatus.Text = Loc.GetString("paper-ui-fill-level",
                    ("currentLength", inputLength),
                    ("maxLength", availableLength));

                // Disable the save button if we've gone over the limit
                SaveButton.Disabled = inputLength > availableLength;
            }
            else
            {
                FillStatus.Text = "";
                SaveButton.Disabled = false;
            }
        }
    }
}
