using System.Numerics;
using System.Linq; // WL-Changes: Structured paper forms
using Content.Client._WL.Paper.UI; // WL-Changes: Structured paper forms
using Content.Client.RichText;
using Content.Shared._WL.Paper; // WL-Changes: Structured paper forms
using Content.Shared.Paper;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.Input;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface; // WL-Changes: Structured paper forms
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;
using Robust.Client.UserInterface.RichText;
using Content.Client.UserInterface.RichText;
using Robust.Shared.Input;
using Robust.Shared.Maths; // WL-Changes: Structured paper forms
using Robust.Shared.Timing; // WL-Changes: Structured paper forms

namespace Content.Client.Paper.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class PaperWindow : BaseWindow
    {
        [Dependency] private IInputManager _inputManager = default!;
        [Dependency] private IResourceCache _resCache = default!;

        private static Color DefaultTextColor = new(25, 25, 25);

        // Default color for text which hasn't been changed using markup
        private Color _writtenTextColor = DefaultTextColor;

        // Size of resize handles around the paper
        private const int DRAG_MARGIN_SIZE = 16;

        // We keep a reference to the paper content texture that we create
        // so that we can modify it later.
        private StyleBoxTexture _paperContentTex = new();

        // The number of lines that the content image represents.
        // See PaperVisualsComponent.ContentImageNumLines.
        private float _paperContentLineScale = 1.0f;

        // If paper limits the size in one or both axes, it'll affect whether
        // we're able to resize this UI or not. Default to everything enabled:
        private DragMode _allowedResizeModes = ~DragMode.None;

        public event Action<string>? OnSaved;

        // WL-Changes-StructuredPaper-Start
        public event Action<string, string>? OnFieldSaved;
        public event Action<string>? OnFieldEditRequested;
        public event Action<string>? OnSignatureRequested;
        public Func<bool>? CanBeginFieldEdit;

        private readonly Dictionary<string, StructuredPaperElement> _renderedFields = new();
        private readonly Dictionary<string, StructuredPaperFieldControl> _fieldControls = new();
        private readonly PaperFieldEditPopup _fieldEditor = new();
        private List<StructuredPaperElement>? _renderedElements;
        private StructuredPaperFieldControl? _activeFieldControl;
        private string? _editingFieldId;
        private int _structuredTextLength;
        private bool _fieldsEditable;
        private bool _renderedDocumentEditable;
        private bool _waitingForFirstLayout;
        private bool _layoutReadinessCheckQueued;
        private int _firstLayoutFrames;
        private static readonly Type[] StructuredPaperAllowedTags =
        [
            ..UserFormattableTags.BaseAllowedTags,
            typeof(StructuredPaperFieldTag),
        ];
        // WL-Changes-StructuredPaper-End

        private int _MaxInputLength = -1;
        public int MaxInputLength
        {
            get
            {
                return _MaxInputLength;
            }
            set
            {
                _MaxInputLength = value;
                UpdateFillState();
            }
        }

        public PaperWindow()
        {
            IoCManager.InjectDependencies(this);
            RobustXamlLoader.Load(this);
            StructuredDocumentContainer.OnResized += UpdateStructuredFieldWidths;

            // We can't configure the RichTextLabel contents from xaml, so do it here:
            BlankPaperIndicator.SetMessage(Loc.GetString("paper-ui-blank-page-message"), null, DefaultTextColor);

            // Hook up the close button:
            CloseButton.OnPressed += _ => Close();

            Input.OnKeyBindDown += args => // Solution while TextEdit don't have events
            {
                if (args.Function == EngineKeyFunctions.MultilineTextSubmit)
                {
                    // SaveButton is disabled when we hit the max input limit. Just check
                    // that flag instead of trying to calculate the input length again
                    if (!SaveButton.Disabled)
                    {
                        RunOnSaved();
                        args.Handle();
                    }
                }
            };

            Input.OnTextChanged += args =>
            {
                UpdateFillState();
            };

            SaveButton.OnPressed += _ =>
            {
                RunOnSaved();
            };

            // WL-Changes-StructuredPaper-Start
            _fieldEditor.OnSaved += text =>
            {
                if (_editingFieldId != null)
                    OnFieldSaved?.Invoke(_editingFieldId, text);
            };
            _fieldEditor.OnPopupHide += CloseFieldEditor;
            OnClose += () => _fieldEditor.Close();
            // WL-Changes-StructuredPaper-End

            SaveButton.Text = Loc.GetString("paper-ui-save-button",
                ("keybind", _inputManager.GetKeyFunctionButtonString(EngineKeyFunctions.MultilineTextSubmit)));
        }

        /// <summary>
        ///     Initialize this UI according to <code>visuals</code> Initializes
        ///     textures, recalculates sizes, and applies some layout rules.
        /// </summary>
        public void InitVisuals(EntityUid entity, PaperVisualsComponent visuals)
        {
            // Randomize the placement of any stamps based on the entity UID
            // so that there's some variety in different papers.
            StampDisplay.PlacementSeed = (int)entity;

            // Initialize the background:
            PaperBackground.ModulateSelfOverride = visuals.BackgroundModulate;
            var backgroundImage = visuals.BackgroundImagePath != null? _resCache.GetResource<TextureResource>(visuals.BackgroundImagePath) : null;
            if (backgroundImage != null)
            {
                var backgroundImageMode = visuals.BackgroundImageTile ? StyleBoxTexture.StretchMode.Tile : StyleBoxTexture.StretchMode.Stretch;
                var backgroundPatchMargin = visuals.BackgroundPatchMargin;
                PaperBackground.PanelOverride = new StyleBoxTexture
                {
                    Texture = backgroundImage,
                    TextureScale = visuals.BackgroundScale,
                    Mode = backgroundImageMode,
                    PatchMarginLeft = backgroundPatchMargin.Left,
                    PatchMarginBottom = backgroundPatchMargin.Bottom,
                    PatchMarginRight = backgroundPatchMargin.Right,
                    PatchMarginTop = backgroundPatchMargin.Top
                };

            }
            else
            {
                PaperBackground.PanelOverride = null;
            }


            // Then the header:
            if (visuals.HeaderImagePath != null)
            {
                HeaderImage.TexturePath = visuals.HeaderImagePath;
                HeaderImage.MinSize = HeaderImage.TextureNormal?.Size ?? Vector2.Zero;
            }

            HeaderImage.ModulateSelfOverride = visuals.HeaderImageModulate;
            HeaderImage.Margin = new Thickness(visuals.HeaderMargin.Left, visuals.HeaderMargin.Top,
                    visuals.HeaderMargin.Right, visuals.HeaderMargin.Bottom);

            // Then the footer
            if (visuals.FooterImagePath is {} path)
            {
                FooterImage.TexturePath = path.ToString();
                FooterImage.MinSize = FooterImage.TextureNormal?.Size ?? Vector2.Zero;
            }

            FooterImage.ModulateSelfOverride = visuals.FooterImageModulate;
            FooterImage.Margin = new Thickness(visuals.FooterMargin.Left, visuals.FooterMargin.Top,
                    visuals.FooterMargin.Right, visuals.FooterMargin.Bottom);

            PaperContent.ModulateSelfOverride = visuals.ContentImageModulate;
            _writtenTextColor = visuals.DefaultTextColor ?? DefaultTextColor;

            var contentImage = visuals.ContentImagePath != null ? _resCache.GetResource<TextureResource>(visuals.ContentImagePath) : null;
            if (contentImage != null)
            {
                // Setup the paper content texture, but keep a reference to it, as we can't set
                // some font-related properties here. We'll fix those up later, in Draw()
                _paperContentTex = new StyleBoxTexture
                {
                    Texture = contentImage,
                    Mode = StyleBoxTexture.StretchMode.Tile,
                };
                PaperContent.PanelOverride = _paperContentTex;
                _paperContentLineScale = visuals.ContentImageNumLines;
            }

            PaperContent.Margin = new Thickness(
                    visuals.ContentMargin.Left, visuals.ContentMargin.Top,
                    visuals.ContentMargin.Right, visuals.ContentMargin.Bottom);

            if (visuals.MaxWritableArea != null)
            {
                var a = (Vector2)visuals.MaxWritableArea;
                // Paper has requested that this has a maximum area that you can write on.
                // So, we'll make the window non-resizable and fix the size of the content.
                // Ideally, would like to be able to allow resizing only one direction.
                ScrollingContents.MinSize = Vector2.Zero;
                ScrollingContents.MinSize = a;

                if (a.X > 0.0f)
                {
                    ScrollingContents.MaxWidth = a.X;
                    _allowedResizeModes &= ~(DragMode.Left | DragMode.Right);

                    // Since this dimension has been specified by the user, we
                    // need to undo the SetSize which was configured in the xaml.
                    // Controls use NaNs to indicate unset for this value.
                    // This is leaky - there should be a method for this
                    SetWidth = float.NaN;
                }

                if (a.Y > 0.0f)
                {
                    ScrollingContents.MaxHeight = a.Y;
                    _allowedResizeModes &= ~(DragMode.Top | DragMode.Bottom);
                    SetHeight = float.NaN;
                }
            }
        }

        /// <summary>
        ///     Control interface. We'll mostly rely on the children to do the drawing
        ///     but in order to get lines on paper to match up with the rich text labels,
        ///     we need to do a small calculation to sync them up.
        /// </summary>
        protected override void Draw(DrawingHandleScreen handle)
        {
            // Now do the deferred setup of the written area. At the point
            // that InitVisuals runs, the label hasn't had it's style initialized
            // so we need to get some info out now:
            if (WrittenTextLabel.TryGetStyleProperty<Font>("font", out var font))
            {
                float fontLineHeight = font.GetLineHeight(1.0f);
                // This positions the texture so the font baseline is on the bottom:
                _paperContentTex.ExpandMarginTop = font.GetDescent(UIScale);
                // And this scales the texture so that it's a single text line:
                var scaleY = (_paperContentLineScale * fontLineHeight) / _paperContentTex.Texture?.Height ?? fontLineHeight;
                _paperContentTex.TextureScale = new Vector2(1, scaleY);

                // Now, we might need to add some padding to the text to ensure
                // that, even if a header is specified, the text will line up with
                // where the content image expects the font to be rendered (i.e.,
                // adjusting the height of the header image shouldn't cause the
                // text to be offset from a line)
                {
                    var headerHeight = HeaderImage.Size.Y + HeaderImage.Margin.Top + HeaderImage.Margin.Bottom;
                    var headerInLines = headerHeight / (fontLineHeight * _paperContentLineScale);
                    var paddingRequiredInLines = (float)Math.Ceiling(headerInLines) - headerInLines;
                    var verticalMargin = fontLineHeight * paddingRequiredInLines * _paperContentLineScale;
                    TextAlignmentPadding.Margin = new Thickness(0.0f, verticalMargin, 0.0f, 0.0f);
                }
            }

            base.Draw(handle);
        }

        /// <summary>
        ///     Initialize the paper contents, i.e. the text typed by the
        ///     user and any stamps that have peen put on the page.
        /// </summary>
        public void Populate(PaperComponent.PaperBoundUserInterfaceState state, bool isEditor)
        {
            bool isEditing = state.Mode == PaperComponent.PaperAction.Write && isEditor;
            // WL-Changes-StructuredPaper-Start
            var isStructured = state.Elements != null;
            var isFreeTextEditing = isEditing && state.EditAccess == PaperEditAccess.FreeText;
            var isFieldEditing = isEditing && state.EditAccess == PaperEditAccess.Fields;
            _structuredTextLength = state.Elements?.Sum(element =>
                element.Text.Length + (element.NewLineAfter ? 1 : 0)) ?? state.Text.Length;
            if (!isEditing)
            {
                _fieldEditor.Close();
                CloseFieldEditor();
            }
            // WL-Changes-StructuredPaper-End
            bool wasEditing = InputContainer.Visible;
            InputContainer.Visible = isFreeTextEditing;
            EditButtons.Visible = isFreeTextEditing;

            // WL-Changes-StructuredPaper-Start
            StructuredDocumentContainer.Visible = isStructured;
            PopulateStructuredDocument(state.Elements, isFieldEditing);
            // WL-Changes-StructuredPaper-End

            // For premade documents, we want to be able to edit them rather than
            // replace them.
            var shouldCopyText = 0 == Input.TextLength && 0 != state.Text.Length && !isStructured;
            if (isFreeTextEditing && (!wasEditing || shouldCopyText))
            {
                // We can get repeated messages with state.Mode == Write if another
                // player opens the UI for reading. In this case, don't update the
                // text input, as this player is currently writing new text and we
                // don't want to lose any text they already input.
                Input.TextRope = Rope.Leaf.Empty;
                Input.CursorPosition = new TextEdit.CursorPos();
                Input.InsertAtCursor(state.Text);
            }

            if (!isStructured)
            {
                var msg = new FormattedMessage();
                msg.AddMarkupPermissive(state.Text);
                for (var i = 0; i <= state.StampedBy.Count * 3 + 1; i++)
                    msg.AddMarkupPermissive("\r\n");

                WrittenTextLabel.SetMessage(msg, UserFormattableTags.BaseAllowedTags, _writtenTextColor);
            }

            WrittenTextLabel.Visible = !isStructured && !isFreeTextEditing && state.Text.Length > 0;
            BlankPaperIndicator.Visible = !isEditing &&
                (!isStructured && state.Text.Length == 0 || isStructured && state.Elements!.Count == 0);

            StampDisplay.RemoveAllChildren();
            StampDisplay.RemoveStamps();
            foreach(var stamper in state.StampedBy)
            {
                // WL-Changes-start
                var stamp = new StampWidget();
                stamp.UpdateVisuals(stamper);

                StampDisplay.AddStamp(stamp);
                // WL-Changes-end
            }
        }

        // WL-Changes-StructuredPaper-Start
        public void PrepareForFirstReveal()
        {
            ModulateSelfOverride = Color.Transparent;
            _waitingForFirstLayout = true;
            _layoutReadinessCheckQueued = false;
            _firstLayoutFrames = 0;
        }

        protected override void FrameUpdate(FrameEventArgs args)
        {
            base.FrameUpdate(args);
            if (!_waitingForFirstLayout || _layoutReadinessCheckQueued)
                return;

            if (++_firstLayoutFrames > 30)
            {
                ModulateSelfOverride = null;
                _waitingForFirstLayout = false;
                return;
            }

            _layoutReadinessCheckQueued = true;
            UserInterfaceManager.DeferAction(() =>
            {
                _layoutReadinessCheckQueued = false;
                if (_waitingForFirstLayout && IsLayoutReady(ContentsRoot))
                {
                    ModulateSelfOverride = null;
                    _waitingForFirstLayout = false;
                }
            });
        }

        private static bool IsLayoutReady(Control control)
        {
            if (!control.Visible && !control.ReservesSpace)
                return true;
            if (!control.IsMeasureValid || !control.IsArrangeValid)
                return false;
            if (control is RichTextLabel label &&
                !string.IsNullOrEmpty(label.GetMessage()) &&
                (label.DesiredSize.Y <= 0 || label.Size.Y <= 0))
                return false;

            return control.Children.All(IsLayoutReady);
        }

        private void PopulateStructuredDocument(List<StructuredPaperElement>? elements, bool editingFields)
        {
            _fieldsEditable = editingFields;
            var canReuseLayout = elements != null &&
                _renderedDocumentEditable == editingFields &&
                CanReuseStructuredDocument(elements);
            if (canReuseLayout)
            {
                UpdateStructuredFields(elements!, editingFields);
                return;
            }

            if (IsOpen && elements != null && _renderedElements == null)
                PrepareForFirstReveal();

            StructuredDocumentContainer.RemoveAllChildren();
            _activeFieldControl = null;
            _fieldControls.Clear();
            _renderedFields.Clear();
            _renderedElements = elements?.Select(element => element.Copy()).ToList();
            _renderedDocumentEditable = editingFields;
            if (elements == null)
                return;

            var label = new RichTextLabel
            {
                HorizontalExpand = true,
                VerticalAlignment = VAlignment.Top,
                StyleClasses = { "PaperWrittenText" },
            };
            label.SetMessage(BuildStructuredMessage(elements, editingFields),
                StructuredPaperAllowedTags,
                _writtenTextColor);
            StructuredDocumentContainer.AddChild(label);
            RegisterStructuredFieldControls(label);
            if (_editingFieldId != null && _fieldControls.TryGetValue(_editingFieldId, out var activeField))
                _activeFieldControl = activeField;
            UpdateStructuredFields(elements, editingFields);
        }

        private void UpdateStructuredFields(IReadOnlyList<StructuredPaperElement> elements, bool editingFields)
        {
            _renderedFields.Clear();
            foreach (var element in elements)
            {
                if (!IsFillableField(element.Type))
                    continue;

                _renderedFields[element.Id] = element.Copy();
                if (!_fieldControls.TryGetValue(element.Id, out var field))
                    continue;

                field.UpdateContent(
                    element.Text,
                    GetRevisions(element),
                    Loc.GetString("paper-ui-form-write-field"),
                    editingFields,
                    element.Id == _editingFieldId,
                    element.HandwritingStyle,
                    element.Type == StructuredPaperElementType.Signature);
            }

            _renderedElements = elements.Select(element => element.Copy()).ToList();
        }

        private static IReadOnlyList<PaperFieldRevision> GetRevisions(StructuredPaperElement element)
        {
            if (string.IsNullOrWhiteSpace(element.PreviousText))
                return element.Revisions;

            var revisions = element.Revisions.Select(revision => revision.Copy()).ToList();
            revisions.Add(new PaperFieldRevision(element.PreviousText, element.PreviousHandwritingStyle));
            return revisions;
        }

        private bool CanReuseStructuredDocument(IReadOnlyList<StructuredPaperElement> elements)
        {
            if (_renderedElements == null || _renderedElements.Count != elements.Count)
                return false;

            for (var i = 0; i < elements.Count; i++)
            {
                var previous = _renderedElements[i];
                var current = elements[i];
                if (previous.Id != current.Id ||
                    previous.Type != current.Type ||
                    previous.NewLineAfter != current.NewLineAfter ||
                    previous.MaxLength != current.MaxLength ||
                    !IsFillableField(current.Type) && previous.Text != current.Text)
                    return false;
            }

            return true;
        }

        private FormattedMessage BuildStructuredMessage(IEnumerable<StructuredPaperElement> elements, bool editable)
        {
            var message = new FormattedMessage();
            foreach (var element in elements)
            {
                if (element.Type == StructuredPaperElementType.StaticText)
                {
                    message.AddMarkupPermissive(element.Text);
                }
                else if (element.Type == StructuredPaperElementType.HandwrittenText)
                {
                    StructuredPaperFieldControl.AddFormattedHandwriting(message, element.Text, element.HandwritingStyle);
                }
                else
                {
                    _renderedFields[element.Id] = element.Copy();
                    var attributes = new Dictionary<string, MarkupParameter>
                    {
                        ["text"] = new(element.Text),
                        ["previous"] = new(element.PreviousText),
                        ["placeholder"] = new(Loc.GetString("paper-ui-form-write-field")),
                        ["editable"] = new(editable ? 1 : 0),
                        ["selected"] = new(element.Id == _editingFieldId ? 1 : 0),
                        ["multiline"] = new(element.Type == StructuredPaperElementType.MultilineField ? 1 : 0),
                        ["signature"] = new(element.Type == StructuredPaperElementType.Signature ? 1 : 0),
                        ["signature-action"] = new(element.Type == StructuredPaperElementType.Signature ? 1 : 0),
                        ["style"] = new((long) element.HandwritingStyle),
                        ["previous-style"] = new((long) element.PreviousHandwritingStyle),
                    };
                    message.PushTag(new MarkupNode(
                        StructuredPaperFieldTag.TagName,
                        new MarkupParameter(element.Id),
                        attributes), true);
                }

                if (element.NewLineAfter)
                    message.PushNewline();
            }

            return message;
        }

        private void RegisterStructuredFieldControls(RichTextLabel label)
        {
            foreach (var control in label.Controls)
            {
                if (control is not StructuredPaperFieldControl field)
                    continue;

                _fieldControls[field.FieldId] = field;
                var fieldId = field.FieldId;
                field.OnPressed += _ =>
                {
                    if (!_renderedFields.TryGetValue(fieldId, out var current))
                        return;

                    if (_fieldsEditable)
                        OpenFieldEditor(current, field);
                    else
                        RequestFieldEditor(fieldId, field);
                };
                field.OnSignatureRequested += () => OnSignatureRequested?.Invoke(fieldId);
            }

            UpdateStructuredFieldWidths();
        }

        private void UpdateStructuredFieldWidths()
        {
            var availableWidth = StructuredDocumentContainer.Width - 8;
            if (availableWidth <= 0)
                return;

            foreach (var field in _fieldControls.Values)
                field.SetDocumentWidth(availableWidth);
        }

        private void RequestFieldEditor(string fieldId, StructuredPaperFieldControl field)
        {
            if (!_renderedFields.TryGetValue(fieldId, out var element))
                return;
            if (CanBeginFieldEdit?.Invoke() == false)
            {
                OnFieldEditRequested?.Invoke(fieldId);
                return;
            }

            OpenFieldEditor(element, field);
        }

        private void OpenFieldEditor(StructuredPaperElement element, StructuredPaperFieldControl field)
        {
            CloseFieldEditor();
            _editingFieldId = element.Id;
            _activeFieldControl = field;
            field.SetSelected(true);

            var remainingPaperLength = MaxInputLength < 0
                ? int.MaxValue
                : Math.Max(0, MaxInputLength - _structuredTextLength + element.Text.Length);
            _fieldEditor.OpenField(element.Type, element.Text, Math.Min(element.GetMaxLength(), remainingPaperLength));
        }

        private void CloseFieldEditor()
        {
            _activeFieldControl?.SetSelected(false);
            _activeFieldControl = null;
            _editingFieldId = null;
        }

        private static bool IsFillableField(StructuredPaperElementType type)
        {
            return type is StructuredPaperElementType.SingleLineField or
                StructuredPaperElementType.MultilineField or
                StructuredPaperElementType.SignatureField or
                StructuredPaperElementType.Signature;
        }
        // WL-Changes-StructuredPaper-End

        /// <summary>
        ///     BaseWindow interface. Allow users to drag UI around by grabbing
        ///     anywhere on the page (like FancyWindow) but try to calculate
        ///     reasonable dragging bounds because this UI can have round corners,
        ///     and it can be hard to judge where to click to resize.
        /// </summary>
        protected override DragMode GetDragModeFor(Vector2 relativeMousePos)
        {
            var mode = DragMode.None;

            // Be quite generous with resize margins:
            if (relativeMousePos.Y < DRAG_MARGIN_SIZE)
            {
                mode |= DragMode.Top;
            }
            else if (relativeMousePos.Y > Size.Y - DRAG_MARGIN_SIZE)
            {
                mode |= DragMode.Bottom;
            }

            if (relativeMousePos.X < DRAG_MARGIN_SIZE)
            {
                mode |= DragMode.Left;
            }
            else if (relativeMousePos.X > Size.X - DRAG_MARGIN_SIZE)
            {
                mode |= DragMode.Right;
            }

            if((mode & _allowedResizeModes) == DragMode.None)
            {
                return DragMode.Move;
            }
            return mode & _allowedResizeModes;
        }

        private void RunOnSaved()
        {
            // Prevent further saving while text processing still in
            SaveButton.Disabled = true;
            OnSaved?.Invoke(Rope.Collapse(Input.TextRope));
        }

        private void UpdateFillState()
        {
            if (MaxInputLength != -1)
            {
                var inputLength = Input.TextLength;

                FillStatus.Text = Loc.GetString("paper-ui-fill-level",
                    ("currentLength", inputLength),
                    ("maxLength", MaxInputLength));

                // Disable the save button if we've gone over the limit
                SaveButton.Disabled = inputLength > MaxInputLength;
            }
            else
            {
                FillStatus.Text = "";
                SaveButton.Disabled = false;
            }
        }
    }
}
